#!/bin/bash

# Exit on error.
set -e

# Verify if any existing mounts are there, warn the user about this.
existing_mounts=$(cat /opt/microsoft/aznfs/mountmap 2>/dev/null | wc -l)
if [ $existing_mounts -ne 0 ]; then
	echo "There are existing Azure Blob NFS mounts using aznfs mount helper, they will not be tracked!"
	echo -n "Are you sure you want to continue? [y/n]: "
	read -n 1 result
	if [ "$result" != "y" -a "$result" != "Y" ]; then
		exit 1
	fi
fi	

# Stop aznfswatchdog service and clean it.
systemctl stop aznfswatchdog
systemctl disable aznfswatchdog
echo "Stopped aznfswatchdog service."
