#
# Release workflow for Mount Helper Script.
#

name: Release to github for Mount Helper

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of Version'
        required: true
      versionCode:
        description: 'Version Number'
        required: true

jobs:
  package_mount_helper:
    name: Package and Release Mount Helper
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Run Package.sh
      shell: bash
      run: |
        export BUILD_NUMBER=${{ github.event.inputs.versionName }}
        export STG_DIR=$GITHUB_WORKSPACE
        export SOURCE_DIR=$GITHUB_WORKSPACE
        chmod +x $GITHUB_WORKSPACE/package.sh
        $GITHUB_WORKSPACE/package.sh
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          # This can be filled.
        tag_name: ${{ github.event.inputs.versionName }}
        name: Release ${{ github.event.inputs.versionName }}
        files: |
          ${{ github.workspace}}/aznfs_1.0.0_amd64.deb
          ${{ github.workspace}}/scripts/installerScript.sh
#     - name: Create Release
#       id: create_release
#       uses: actions/create_release@v2
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         tag_name: ${{ github.ref }}
#         release_name: Release ${{ github.ref }}
#         body: |
#           # This could be filled depends on the release.ref
#         draft: false
#         prerelease: false
#     - name: Upload Release Asset
#       id: upload-release-asset
#       uses: actions/upload-release-asset@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upload_url: ${{ steps.crete_release.outputs.upload_url }}
#         asset_path: ./aznfs.deb
#         asset_name: aznfs.deb
